--- 
apiVersion: v1
kind: Pod
metadata: 
  name: contracts223
  labels: 
    app: main
    env: prod
    owner: AntonZhivnov
    tier: backend 
spec:
  volumes: 
    - name: downloads
      emptyDir: {}
    - name: configs
      gitRepo:
        repository: "https://github.com/zhvant/UniversalIntegratorPods.git"
      #emptyDir: {}
      #type: Directory
      #hostPath:
      #  path: /home/docker/configs
          
  containers: 
  
    - image: zhvant/universalintegrator
      name: container-downloader
      volumeMounts: 
        - mountPath: /app/downloads
          name: downloads
        - mountPath: /app/configs
          name: configs
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "/bin/cp /app/configs/UniversalIntegratorPods/$HOSTNAME/container-downloader/Config.json /app/Config.json"]

    - image: zhvant/universalintegrator
      name: container-archiver
      volumeMounts: 
        - mountPath: /app/downloads
          name: downloads
        - mountPath: /app/configs
          name: configs
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "/bin/cp /app/configs/UniversalIntegratorPods/$HOSTNAME/container-archiver/Config.json /app/Config.json"]


