--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: main
    env: prod
    owner: AntonZhivnov
    tier: backend
  name: contracts223
spec:
  volumes: 
    - name: downloads
      emptyDir: {}
    - name: configs
      emptyDir: {}
      #type: Directory
      #hostPath:
      #  path: /home/docker/configs
          
  containers: 
    - 
      image: zhvant/universalintegrator
      name: container-downloader
      volumeMounts: 
        - 
          mountPath: /app/downloads
          name: downloads
        - 
          mountPath: /app/configs
          name: configs
    - 
      image: zhvant/universalintegrator
      name: container-unarchiever
      volumeMounts: 
        - 
          mountPath: /app/downloads
          name: downloads
        - 
          mountPath: /app/configs
          name: configs

