--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: notifications223
  labels: 
    app: main
    env: dev
    owner: AntonZhivnov
    tier: backend 
spec:
  volumes: 
    - name: configs
      emptyDir: {}
    - name: config
      emptyDir: {}

  initContainers:    
   - name: init
     image: bitnami/git
     command: ["/bin/sh","-c"
     ,"git clone 
     https://github.com/zhvant/UniversalIntegratorPods.git
     /app/configs 
     && 
     cp /app/configs/$POD_NAME/container/Config.json /app/config/Config.json
     "]
     volumeMounts:
     - mountPath: /app/configs
       name: configs
     - mountPath: /app/config
       name: config
     env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

  containers:   
    - image: zhvant/universalintegrator
      name: container
      volumeMounts: 
        - mountPath: /app/config
          name: config
